controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AdForm;
use app\models\User;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Ad;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $query = Ad::find()
            ->select([Ad::tableName().'.id', 'title', 'description','user_id',Ad::tableName().'.created_at',User::tableName().'.username'])
            ->leftJoin(User::tableName(), User::tableName().'.id = '.Ad::tableName().'.user_id')
            ->orderBy([Ad::tableName().'.created_at' => SORT_DESC])
            ->asArray();
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 5, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('index', [
            'models' => $models,
            'pages' => $pages,
        ]);

    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->login()){
                return $this->goBack();
            } elseif (is_null(User::findByUsername($model->username))) {
                if($this->signup($model)) {
                    return $this->goHome();
                }
            }
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Singup action
     *
     * @return Response|string
     */
    private function signup($model)
    {
        $model->username = trim($model->username);
        $model->password = trim($model->password);
        if ($model->username && $model->password) {
            if (iconv_strlen($model->password)>=6) {
                $user = new User();
                $user->username = $model->username;
                $user->setPassword($model->password);
                $user->generateAuthKey();
                $user->save();
                Yii::$app->user->login($user);
                return true;
            }
        }

        return false;
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionDelete($id)
    {
        $ad = Ad::findOne($id);
        $ad->delete();
        return $this->goHome();
    }

    /**
     * View Ad
     * @param $ad_id
     * @return string
     */
    public function actionView($id)
    {
        $ad = Ad::find()
            ->where(['id' => $id])
            ->one();
        return $this->render('view', [
            'ad' => $ad,
        ]);
    }


    public function actionEdit($id = null)
    {
        $model = new AdForm();

        if (!is_null($id)){
            $model = $this->findModel($id);
            if ($model->load(Yii::$app->request->post())) {
                if ($model->save()) {
                    return $this->actionView($model->id);
                }

            }
            return $this->render('edit', [
                'model' => $model,
            ]);
        }
        if ($model->load(Yii::$app->request->post())) {
            if ($ad = $model->saveAd()) {
                return $this->actionView($ad->id);
            }
        }
        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Ad::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/footer.php
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy;Ads Board <?= date('Y') ?></p>
    </div>
</footer>

views/layouts/header.php
<?php

use yii\bootstrap\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);
echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'items' => [
        ['label' => 'Main', 'url' => ['/site/index']],
        ['label' => 'Create Ad', 'url' => ['site/edit'], 'visible' => !Yii::$app->user->isGuest],
        Yii::$app->user->isGuest ?
            (
            ['label' => 'Log In', 'url' => ['/site/login']]
            )
            :
            (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Log Out (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
    ],
]);
NavBar::end();
?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?= Yii::$app->controller->renderPartial('//layouts/header'); ?>
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>
<?= Yii::$app->controller->renderPartial('//layouts/footer'); ?>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>