controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AdForm;
use app\models\User;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Ad;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $query = Ad::find()
            ->select([Ad::tableName().'.id', 'title', 'description','user_id',Ad::tableName().'.created_at',User::tableName().'.username'])
            ->leftJoin(User::tableName(), User::tableName().'.id = '.Ad::tableName().'.user_id')
            ->orderBy([Ad::tableName().'.created_at' => SORT_DESC])
            ->asArray();
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 5, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('index', [
            'models' => $models,
            'pages' => $pages,
        ]);

    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->login()){
                return $this->goBack();
            } elseif (is_null(User::findByUsername($model->username))) {
                if($this->signup($model)) {
                    return $this->goHome();
                }
            }
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Singup action
     *
     * @return Response|string
     */
    private function signup($model)
    {
        $model->username = trim($model->username);
        $model->password = trim($model->password);
        if ($model->username && $model->password) {
            if (iconv_strlen($model->password)>=6) {
                $user = new User();
                $user->username = $model->username;
                $user->setPassword($model->password);
                $user->generateAuthKey();
                $user->save();
                Yii::$app->user->login($user);
                return true;
            }
        }

        return false;
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionDelete($id)
    {
        $ad = Ad::findOne($id);
        $ad->delete();
        return $this->goHome();
    }

    /**
     * View Ad
     * @param $ad_id
     * @return string
     */
    public function actionView($id)
    {
        $ad = Ad::find()
            ->where(['id' => $id])
            ->one();
        return $this->render('view', [
            'ad' => $ad,
        ]);
    }


    public function actionEdit($id = null)
    {
        $model = new AdForm();

        if (!is_null($id)){
            $model = $this->findModel($id);
            if ($model->load(Yii::$app->request->post())) {
                if ($model->save()) {
                    return $this->actionView($model->id);
                }

            }
            return $this->render('edit', [
                'model' => $model,
            ]);
        }
        if ($model->load(Yii::$app->request->post())) {
            if ($ad = $model->saveAd()) {
                return $this->actionView($ad->id);
            }
        }
        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Ad::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/site/edit.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Create Ad';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-ad">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-lg-offset-3 col-lg-6">
            <?php $form = ActiveForm::begin(['id' => 'form-ad']); ?>
            <?= $form->field($model, 'title')->textInput(['autofocus' => true]) ?>
            <?= $form->field($model, 'description')->textarea() ?>
            <div class="form-group">
                <?= Html::submitButton('Create', ['class' => 'btn btn-primary', 'name' => 'ad-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/error.php
?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\widgets\LinkPager;
use yii\web\UrlManager;
/* @var $this yii\web\View */

$this->title = 'Main page';
?>
<div class="container">
    <?php foreach ($models as $model): ?>
        <div class="row">
            <div class="panel">
                <div class="panel-heading d-flex justify-content-between bg-info panel-danger">
                    <div class="row">
                        <div class="col-lg-3">
                            <a href="<?=\yii\helpers\Url::toRoute(['site/view', 'id' => $model['id']]) ?>" style="text-decoration: none; color: #000000;"><h3 class="p-2 text-left"><?= $model['title'] ?></h3></a>
                        </div>
                        <div class="col-lg-offset-6 col-lg-3">
                            <p class="text-right" style="font-size: 15px;"><?= $model['username'] ?></p>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <p style="font-size: 16px;"><?= $model['description'] ?></p>
                </div>
                <?php if ($model['user_id'] == Yii::$app->user->id): ?>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-lg-1">
                                <a href="<?=\yii\helpers\Url::toRoute(['/site/view', 'id' => $model['id']]) ?>"><div class="fa fa-eye" href="" style="font-size: 14px; color: #4cae4c;"></div></a>
                                <a href="<?=\yii\helpers\Url::toRoute(['/site/delete', 'id' => $model['id']]) ?>"><div class="fa fa-trash-alt" href="" style="font-size: 14px; color: #bd2130;"></div></a>
                                <a href="<?=\yii\helpers\Url::toRoute(['/site/edit', 'id' => $model['id']]) ?>"><div class="fa fa-edit" style="font-size: 14px;"></div></a>
                            </div>
                            <div class="col-lg-offset-9 col-lg-2 ">
                                <em><p class="text-right" style="font-size: 12px;"><?= date('Y-m-d H:i:s', $model['created_at']); ?></p></em>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-lg-1">
                                <a href="<?=\yii\helpers\Url::toRoute(['/site/view', 'id' => $model['id']]) ?>"><div class="fa fa-eye" href="" style="font-size: 14px; color: #4cae4c;"></div></a>
                            </div>
                            <div class="col-lg-offset-9 col-lg-2 ">
                                <em><p class="text-right" style="font-size: 12px;"><?= date('Y-m-d H:i:s', $model['created_at']); ?></p></em>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>

    <?= LinkPager::widget([
        'pagination' => $pages,
    ]); ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/view.php
<?php
/**
 * Created by PhpStorm.
 * User: panda
 * Date: 03.08.18
 * Time: 21:24
 */
$this->title = $ad->title;
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="row">
        <div class="col-lg-12">
            <h2><?= $ad->title; ?></h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p><?= $ad->description; ?></p>
        </div>
    </div>

    <p class="text-right">Author: <b><?= $ad->user->username; ?></b></p>
    <p class="text-right">Date: <b><?= date('Y-m-d H:i:s', $ad->created_at); ?></b></p>
<?php if ($ad->user->id === Yii::$app->user->id): ?>
    <a href="<?=\yii\helpers\Url::toRoute(['/site/delete', 'id' => $ad->id]) ?>"><div class="fa fa-trash-alt" href="" style="font-size: 14px; color: #bd2130;"></div></a>
    <a href="<?=\yii\helpers\Url::toRoute(['/site/edit', 'id' => $ad->id]) ?>"><div class="fa fa-edit" style="font-size: 14px;"></div></a>
<?php endif; ?>